version: '3.9'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lock
      POSTGRES_PASSWORD: lock
      POSTGRES_DB: lock
    volumes:
      - ../data/postgresql:/var/lib/postgresql/data

