server:
  port: 3000
  shutdown: graceful
spring:
  application:
    name: lock
  datasource:
    url: jdbc:postgresql://localhost:5432/lock
    username: lock
    password: lock
  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
springdoc:
  api-docs:
    path: /api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  swagger-ui:
    path: /
logging:
  level:
    root: INFO

