CREATE TABLE products_optimistic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE products_pessimistic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock BIGINT NOT NULL
);



INSERT INTO products_optimistic (id, stock, version)
VALUES
    (1, 10, 1),
    (2, 10, 1),
    (3, 10, 1);


INSERT INTO products_pessimistic(id, stock)
VALUES
    (1, 10),
    (2, 10),
    (3, 10);

